### ISSUE TITLE
Kubernetes vagrantfile MANAGE_FROM_HOST setting to true not working.

### ISSUE THREAD

**Issue by rvshukla97** [oracle/vagrant-boxes#100] opened 2019-02-23 07:17 UTC
In Kubernetes vagrantfile changed MANAGE_FROM_HOST flag to true to access Kubernetes from vagrant host. Using admin.conf generated in vagrant host to connect to kubenetes cluster from kubectl.
Command:
$ kubectl get nodes
Output:
Unable to connect to the server: x509: certificate is valid for 10.96.0.1, 192.168.99.100, not 127.0.0.1

Please help to resolve this issue.

**Comment by AmedeeBulle** [comment] 2019-02-23 10:58
This is a regression with the release of the 1.12.

I'll fix that, but in the meantime as workaround you should be able to use the VirtualBox host network.
Change the server address in `admin.conf` to `192.168.99.100` and you should be good:
```
[amedee@bommel Kubernetes]$ diff  admin.conf.orig admin.conf 
5c5
<     server: https://127.0.0.1:6443
---
>     server: https://192.168.99.100:6443
```

```
[amedee@bommel Kubernetes]$ kubectl get nodes
NAME                 STATUS   ROLES    AGE   VERSION
master.vagrant.vm    Ready    master   8d    v1.12.5+2.1.1.el7
worker1.vagrant.vm   Ready    <none>   8d    v1.12.5+2.1.1.el7
worker2.vagrant.vm   Ready    <none>   8d    v1.12.5+2.1.1.el7
```

**Comment by rvshukla97** [comment] 2019-02-24 13:22
As per the workaround, I have changed the IP to 192.168.99.100 but still i am observing following issue,
Command:
`$ kubectl get nodes`

Output after a long pause:
`Unable to connect to the server: net/http: TLS handshake timeout`

**Comment by AmedeeBulle** [comment] 2019-02-24 21:53
- What is the host OS?
- Can you verify you don't have firewall rules on the host preventing connection?

**Comment by rvshukla97** [comment] 2019-02-25 03:00
The host os is "Oracle Linux 7.6"
I have stopped the firewall, 
`[ravishuk@linux Kubernetes]$ sudo systemctl status firewalld
[sudo] password for ravishuk: 
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Mon 2019-02-25 08:07:51 IST; 17min ago
     Docs: man:firewalld(1)
  Process: 4324 ExecStart=/usr/sbin/firewalld --nofork --nopid $FIREWALLD_ARGS (code=exited, status=0/SUCCESS)
 Main PID: 4324 (code=exited, status=0/SUCCESS)

Feb 25 08:04:01 linux systemd[1]: Starting firewalld - dynamic firewall daemon...
Feb 25 08:04:02 linux systemd[1]: Started firewalld - dynamic firewall daemon.
Feb 25 08:07:51 linux systemd[1]: Stopping firewalld - dynamic firewall daemon...
Feb 25 08:07:51 linux systemd[1]: Stopped firewalld - dynamic firewall daemon.
`
But still I am having the same issue,
`[ravishuk@linux Kubernetes]$ kubectl get nodes
Unable to connect to the server: net/http: TLS handshake timeout
[ravishuk@linux Kubernetes]$ vim admin.conf
[ravishuk@linux Kubernetes]$ kubectl --insecure-skip-tls-verify get nodes
Unable to connect to the server: net/http: TLS handshake timeout
`

**Comment by rvshukla97** [comment] 2019-02-25 06:01
With server IP 127.0.0.1 in admin.conf, I am able to connect from host,  using kubectl --insecure-skip-tls-verify flag.
```
[ravishuk@linux Kubernetes]$ kubectl --insecure-skip-tls-verify get nodes
NAME                STATUS   ROLES    AGE     VERSION
master.vagrant.vm   Ready    master   3h12m   v1.12.5+2.1.1.el7
```

**Comment by AmedeeBulle** [comment] 2019-02-25 15:50
Discussed with Ravi:
- The workaround using host networking wasn't working because a VPN connection was preventing access to local networks.
- The pull request #101 fixes the original issue.

Closing.

**Closed by AmedeeBulle** 2019-02-25 15:50 UTC
Labels: bug, kubernetes
