### ISSUE TITLE
problems with yum "Metadata file does not match checksum"

### ISSUE THREAD

**Issue by Harald-P** [oracle/vagrant-boxes#222] opened 2020-04-23 21:28 UTC
Hi,

starting a fresh box i recive this error:

    oracle-12201-vagrant: INSTALLER: Started up
    oracle-12201-vagrant: http://yum.oracle.com/repo/OracleLinux/OL7/latest/x86_64/repodata/89bd3f0b88ea05f0c38ac7cf1d51846ca5273415-updateinfo.xml.gz: [Errno -1] Metadata file does not match checksum

**More details:**

vagrant-boxes-master\OracleDatabase\12.2.0.1> vagrant up
Installing vagrant-proxyconf Plugin...
Installing the 'vagrant-proxyconf' plugin. This can take a few minutes...
Fetching: vagrant-proxyconf-2.0.7.gem (100%)
Installed the plugin 'vagrant-proxyconf (2.0.7)'!
Bringing machine 'oracle-12201-vagrant' up with 'virtualbox' provider...
==> oracle-12201-vagrant: Box 'oraclelinux/7' could not be found. Attempting to find and install...
    oracle-12201-vagrant: Box Provider: virtualbox
    oracle-12201-vagrant: Box Version: >= 0
==> oracle-12201-vagrant: Loading metadata for box 'https://oracle.github.io/vagrant-boxes/boxes/oraclelinux/7.json'
    oracle-12201-vagrant: URL: https://oracle.github.io/vagrant-boxes/boxes/oraclelinux/7.json
==> oracle-12201-vagrant: Adding box 'oraclelinux/7' (v7.8.103) for provider: virtualbox
    oracle-12201-vagrant: Downloading: https://yum.oracle.com/boxes/oraclelinux/ol7/ol7u8-virtualbox-b103.box
    oracle-12201-vagrant:
    oracle-12201-vagrant: Calculating and comparing box checksum...
==> oracle-12201-vagrant: Successfully added box 'oraclelinux/7' (v7.8.103) for 'virtualbox'!
==> oracle-12201-vagrant: Importing base box 'oraclelinux/7'...
==> oracle-12201-vagrant: Matching MAC address for NAT networking...
==> oracle-12201-vagrant: Checking if box 'oraclelinux/7' version '7.8.103' is up to date...
==> oracle-12201-vagrant: Setting the name of the VM: oracle-12201-vagrant
==> oracle-12201-vagrant: Clearing any previously set network interfaces...
==> oracle-12201-vagrant: Preparing network interfaces based on configuration...
    oracle-12201-vagrant: Adapter 1: nat
==> oracle-12201-vagrant: Forwarding ports...
    oracle-12201-vagrant: 1521 (guest) => 1521 (host) (adapter 1)
    oracle-12201-vagrant: 5500 (guest) => 5500 (host) (adapter 1)
    oracle-12201-vagrant: 22 (guest) => 2222 (host) (adapter 1)
==> oracle-12201-vagrant: Running 'pre-boot' VM customizations...
==> oracle-12201-vagrant: Booting VM...
==> oracle-12201-vagrant: Waiting for machine to boot. This may take a few minutes...
    oracle-12201-vagrant: SSH address: 127.0.0.1:2222
    oracle-12201-vagrant: SSH username: vagrant
    oracle-12201-vagrant: SSH auth method: private key
    oracle-12201-vagrant:
    oracle-12201-vagrant: Vagrant insecure key detected. Vagrant will automatically replace
    oracle-12201-vagrant: this with a newly generated keypair for better security.
    oracle-12201-vagrant:
    oracle-12201-vagrant: Inserting generated public key within guest...
    oracle-12201-vagrant: Removing insecure key from the guest if it's present...
    oracle-12201-vagrant: Key inserted! Disconnecting and reconnecting using new SSH key...
==> oracle-12201-vagrant: Machine booted and ready!
==> oracle-12201-vagrant: Checking for guest additions in VM...
==> oracle-12201-vagrant: Setting hostname...
==> oracle-12201-vagrant: Mounting shared folders...
    oracle-12201-vagrant: /vagrant => D:/VMs/vagrant-boxes-master/OracleDatabase/12.2.0.1
==> oracle-12201-vagrant: Running provisioner: shell...
    oracle-12201-vagrant: Running: C:/Users/Harald/AppData/Local/Temp/vagrant-shell20200423-7620-6psu6u.sh
    oracle-12201-vagrant: INSTALLER: Started up
    oracle-12201-vagrant: http://yum.oracle.com/repo/OracleLinux/OL7/latest/x86_64/repodata/89bd3f0b88ea05f0c38ac7cf1d51846ca5273415-updateinfo.xml.gz: [Errno -1] Metadata file does not match checksum
    oracle-12201-vagrant: Trying other mirror.
    oracle-12201-vagrant: http://yum.oracle.com/repo/OracleLinux/OL7/optional/latest/x86_64/repodata/6e67ed6f455bf1a0fec5fb214b0278a4c0e58c37-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    oracle-12201-vagrant: Trying other mirror.
    oracle-12201-vagrant: http://yum.oracle.com/repo/OracleLinux/OL7/latest/x86_64/repodata/e9e948d118c78cc246106b2b16e963c2b2a46fce-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    oracle-12201-vagrant: Trying other mirror.
    oracle-12201-vagrant: http://yum.oracle.com/repo/OracleLinux/OL7/SoftwareCollections/x86_64/repodata/06b91fb385ab1e66ed5b0ce909c88f40e0f189d9-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    oracle-12201-vagrant: Trying other mirror.
    oracle-12201-vagrant: http://yum.oracle.com/repo/OracleLinux/OL7/UEKR5/x86_64/repodata/2686da7e19aff485712781b237a76a80cd869c58-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    oracle-12201-vagrant: Trying other mirror.
    oracle-12201-vagrant: http://yum.oracle.com/repo/OracleLinux/OL7/optional/latest/x86_64/repodata/6e67ed6f455bf1a0fec5fb214b0278a4c0e58c37-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    oracle-12201-vagrant: Trying other mirror.
    oracle-12201-vagrant: http://yum.oracle.com/repo/OracleLinux/OL7/SoftwareCollections/x86_64/repodata/06b91fb385ab1e66ed5b0ce909c88f40e0f189d9-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    oracle-12201-vagrant: Trying other mirror.
    oracle-12201-vagrant: http://yum.oracle.com/repo/OracleLinux/OL7/UEKR5/x86_64/repodata/2686da7e19aff485712781b237a76a80cd869c58-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    oracle-12201-vagrant: Trying other mirror.
    oracle-12201-vagrant: http://yum.oracle.com/repo/OracleLinux/OL7/UEKR5/x86_64/repodata/2686da7e19aff485712781b237a76a80cd869c58-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    oracle-12201-vagrant: Trying other mirror.
    oracle-12201-vagrant:
    oracle-12201-vagrant:
    oracle-12201-vagrant:  One of the configured repositories failed (Latest Unbreakable Enterprise Kernel Release 5 for Oracle Linux 7Server (x86_64)),
    oracle-12201-vagrant:  and yum doesn't have enough cached data to continue. At this point the only
    oracle-12201-vagrant:  safe thing yum can do is fail. There are a few ways to work "fix" this:
    oracle-12201-vagrant:
    oracle-12201-vagrant:      1. Contact the upstream for the repository and get them to fix the problem.
    oracle-12201-vagrant:
    oracle-12201-vagrant:      2. Reconfigure the baseurl/etc. for the repository, to point to a working
    oracle-12201-vagrant:         upstream. This is most often useful if you are using a newer
    oracle-12201-vagrant:         distribution release than is supported by the repository (and the
    oracle-12201-vagrant:         packages for the previous distribution release still work).
    oracle-12201-vagrant:
    oracle-12201-vagrant:      3. Run the command with the repository temporarily disabled
    oracle-12201-vagrant:             yum --disablerepo=ol7_UEKR5 ...
    oracle-12201-vagrant:
    oracle-12201-vagrant:      4. Disable the repository permanently, so yum won't use it by default. Yum
    oracle-12201-vagrant:         will then just ignore the repository until you permanently enable it
    oracle-12201-vagrant:         again or use --enablerepo for temporary usage:
    oracle-12201-vagrant:
    oracle-12201-vagrant:             yum-config-manager --disable ol7_UEKR5
    oracle-12201-vagrant:         or
    oracle-12201-vagrant:             subscription-manager repos --disable=ol7_UEKR5
    oracle-12201-vagrant:
    oracle-12201-vagrant:      5. Configure the failing repository to be skipped, if it is unavailable.
    oracle-12201-vagrant:         Note that yum will try to contact the repo. when it runs most commands,
    oracle-12201-vagrant:         so will have to try and fail each time (and thus. yum will be be much
    oracle-12201-vagrant:         slower). If it is a very temporary problem though, this is often a nice
    oracle-12201-vagrant:         compromise:
    oracle-12201-vagrant:
    oracle-12201-vagrant:             yum-config-manager --save --setopt=ol7_UEKR5.skip_if_unavailable=true
    oracle-12201-vagrant:
    oracle-12201-vagrant: failure: repodata/2686da7e19aff485712781b237a76a80cd869c58-primary.sqlite.bz2 from ol7_UEKR5: [Errno 256] No more mirrors to try.
    oracle-12201-vagrant: http://yum.oracle.com/repo/OracleLinux/OL7/UEKR5/x86_64/repodata/2686da7e19aff485712781b237a76a80cd869c58-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

The same Problem with the 19.3.0 - Version.

Kind regards

**Comment by Djelibeybi** [comment] 2020-04-23 21:30
This can happen when the Akamai CDN nodes that host yum.oracle.com get out of sync. Usually I give it an hour or two and try again. It's also worth updating your base Oracle Linux 7 box to the latest version because using the `https` URLs tends to work better than the plain `http` ones (less caching involved by intermediates).

**Comment by Harald-P** [comment] 2020-04-23 21:39
Thanks for your immediate reply.

I am new to Vagrant and Linux. I was thinking that i must only go in the correspondent directory (in my case \vagrant-boxes-master\OracleDatabase\12.2.0.1) and write "vagrant up" and the scripts get all that its needed. But it seems that i have not understand well the concept and i must prepare something before i go in the directory an write "vagrant up".

Where is the base box and how can i get and update the base Oracle Linux 7 box?

Kind regards

**Comment by Djelibeybi** [comment] 2020-04-23 21:42
Is this a brand-new clone of the git repo? We recently merged some fixes a couple of days ago that updated the way we refer to upstream boxes. If you haven't already, it might be worth doing a `git pull` on your clone of the repo to make sure you have the latest version.

**Comment by Harald-P** [comment] 2020-04-23 21:49
yes it is brand-new, i have downloaded today vagrant-boxes-master.zip...
So its maybe a bug in the new version?

**Comment by Djelibeybi** [comment] 2020-04-23 21:53
My initial build is working fine, though that doesn't mean there isn't an issue with our CDN. I am almost certainly using a different CDN node than you.

**Comment by Harald-P** [comment] 2020-04-23 21:57
where can i tune to use the right CDN?

**Comment by Djelibeybi** [comment] 2020-04-23 22:00
You can't, unfortunately. It's done automaticaly based on your region. I just want to validate certain things inside the DB build itself.

**Comment by mark-au** [comment] 2020-04-23 22:01
For interest: https://en.wikipedia.org/wiki/Content_delivery_network

**Comment by Harald-P** [comment] 2020-04-23 22:06
ok, so i understand that i must wait till my CDN is synched

thanks to both for your help!

**Comment by Djelibeybi** [comment] 2020-04-23 22:08
I have spotted an inefficiency in the way we configure our repos, so I'm raising that internally. In the interim, I'll see if I can work out a simple way for you to workaround this issue.

**Comment by Harald-P** [comment] 2020-04-23 22:12
a workaround will be fine for me :-)

**Comment by Djelibeybi** [comment] 2020-04-23 22:23
Can you please add `sed -i 's|http://yum\$ociregion.oracle.com|https://yum\$ociregion.oracle.com|g' /etc/yum.repos.d/*.repo` to `scripts/install.sh` _before_ the `yum upgrade -y` command on line 20? See if that works.

**Comment by Harald-P** [comment] 2020-04-24 06:03
it doesn't work, i have done:

echo 'INSTALLER: Started up'
sed -i 's|http://yum\$ociregion.oracle.com|https://yum\$ociregion.oracle.com|g' /etc/yum.repos.d/*.repo
# get up to date
yum upgrade -y

echo 'INSTALLER: System updated'

**Result:**

    oracle-12201-vagrant: INSTALLER: Started up
    oracle-12201-vagrant: https://yum.oracle.com/repo/OracleLinux/OL7/latest/x86_64/repodata/f057575864a8a5d3fa0776c8abc76b8c8b53ef0a-updateinfo.xml.gz: [Errno -1] Metadata file does not match checksum
    oracle-12201-vagrant: Trying other mirror.
    oracle-12201-vagrant: https://yum.oracle.com/repo/OracleLinux/OL7/optional/latest/x86_64/repodata/52fbd7b08fa64011f7655f578442e00279ddd997-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    oracle-12201-vagrant: Trying other mirror.
    oracle-12201-vagrant: https://yum.oracle.com/repo/OracleLinux/OL7/SoftwareCollections/x86_64/repodata/cae4bb00275acb0dd315ca9d39e957c5d8b2d09d-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    oracle-12201-vagrant: Trying other mirror.
    oracle-12201-vagrant: https://yum.oracle.com/repo/OracleLinux/OL7/UEKR5/x86_64/repodata/2686da7e19aff485712781b237a76a80cd869c58-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    oracle-12201-vagrant: Trying other mirror.
    oracle-12201-vagrant: https://yum.oracle.com/repo/OracleLinux/OL7/optional/latest/x86_64/repodata/52fbd7b08fa64011f7655f578442e00279ddd997-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    oracle-12201-vagrant: Trying other mirror.
    oracle-12201-vagrant: https://yum.oracle.com/repo/OracleLinux/OL7/SoftwareCollections/x86_64/repodata/cae4bb00275acb0dd315ca9d39e957c5d8b2d09d-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    oracle-12201-vagrant: Trying other mirror.
    oracle-12201-vagrant: https://yum.oracle.com/repo/OracleLinux/OL7/UEKR5/x86_64/repodata/2686da7e19aff485712781b237a76a80cd869c58-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    oracle-12201-vagrant: Trying other mirror.
    oracle-12201-vagrant: https://yum.oracle.com/repo/OracleLinux/OL7/UEKR5/x86_64/repodata/2686da7e19aff485712781b237a76a80cd869c58-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
    oracle-12201-vagrant: Trying other mirror.
    oracle-12201-vagrant:
    oracle-12201-vagrant:
    oracle-12201-vagrant:  One of the configured repositories failed (Latest Unbreakable Enterprise Kernel Release 5 for Oracle Linux 7Server (x86_64)),
    oracle-12201-vagrant:  and yum doesn't have enough cached data to continue. At this point the only
    oracle-12201-vagrant:  safe thing yum can do is fail. There are a few ways to work "fix" this:
    oracle-12201-vagrant:
    oracle-12201-vagrant:      1. Contact the upstream for the repository and get them to fix the problem.
    oracle-12201-vagrant:
    oracle-12201-vagrant:      2. Reconfigure the baseurl/etc. for the repository, to point to a working
    oracle-12201-vagrant:         upstream. This is most often useful if you are using a newer
    oracle-12201-vagrant:         distribution release than is supported by the repository (and the
    oracle-12201-vagrant:         packages for the previous distribution release still work).
    oracle-12201-vagrant:
    oracle-12201-vagrant:      3. Run the command with the repository temporarily disabled
    oracle-12201-vagrant:             yum --disablerepo=ol7_UEKR5 ...
    oracle-12201-vagrant:
    oracle-12201-vagrant:      4. Disable the repository permanently, so yum won't use it by default. Yum
    oracle-12201-vagrant:         will then just ignore the repository until you permanently enable it
    oracle-12201-vagrant:         again or use --enablerepo for temporary usage:
    oracle-12201-vagrant:
    oracle-12201-vagrant:             yum-config-manager --disable ol7_UEKR5
    oracle-12201-vagrant:         or
    oracle-12201-vagrant:             subscription-manager repos --disable=ol7_UEKR5
    oracle-12201-vagrant:
    oracle-12201-vagrant:      5. Configure the failing repository to be skipped, if it is unavailable.
    oracle-12201-vagrant:         Note that yum will try to contact the repo. when it runs most commands,
    oracle-12201-vagrant:         so will have to try and fail each time (and thus. yum will be be much
    oracle-12201-vagrant:         slower). If it is a very temporary problem though, this is often a nice
    oracle-12201-vagrant:         compromise:
    oracle-12201-vagrant:
    oracle-12201-vagrant:             yum-config-manager --save --setopt=ol7_UEKR5.skip_if_unavailable=true
    oracle-12201-vagrant:
    oracle-12201-vagrant: failure: repodata/2686da7e19aff485712781b237a76a80cd869c58-primary.sqlite.bz2 from ol7_UEKR5: [Errno 256] No more mirrors to try.
    oracle-12201-vagrant: https://yum.oracle.com/repo/OracleLinux/OL7/UEKR5/x86_64/repodata/2686da7e19aff485712781b237a76a80cd869c58-primary.sqlite.bz2: [Errno -1] Metadata file does not match checksum
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by Harald-P** [comment] 2020-04-24 06:04
sorry for the bad formatting...

**Comment by AmedeeBulle** [comment] 2020-04-24 07:29
This looks very similar to #215 / #216 ...
We never found the root cause, but seemed to be a combination of the VirtualBox version and HyperV settings...

**Comment by Harald-P** [comment] 2020-04-24 08:04
So it seems to be a problem with hyper-v...

i solved it with:
> bcdedit /set hypervisorlaunchtype off
> (To enable:
> bcdedit /set hypervisorlaunchtype auto)
> 
> Need to restart the host after the change..._

I had this problem on two very different Windows 10 hosts, but on both i used Hyper-V...

So many thanks for your help

**Comment by Djelibeybi** [comment] 2020-04-24 19:37
Glad it fixed the problem! I'm an Apple user, so I didn't even think about Hyper-V here. I'm going to close this issue, but feel free to open a new one if you have further questions.

**Closed by Djelibeybi** 2020-04-24 19:37 UTC
