### ISSUE TITLE
Error response from daemon: OCI runtime create failed

### ISSUE THREAD

**Issue by ppengkkang** [oracle/vagrant-boxes#120] opened 2019-04-24 07:28 UTC
Warning  Failed            46m                 kubelet, worker2.vagrant.vm  Error: failed to start container "redis": Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:58: mounting \\\"/var/lib/docker/containers/580067f71fdb3e160cccd4cb0c11b2a50e625f2db8ba974677ed43ad839897e0/resolv.conf\\\" to rootfs \\\"/var/lib/docker/btrfs/subvolumes/9e0aa231ac7e714db5f7a496cfe0c3836d1b28326085f3eeb532747afff1b3bd\\\" at \\\"/var/lib/docker/btrfs/subvolumes/9e0aa231ac7e714db5f7a496cfe0c3836d1b28326085f3eeb532747afff1b3bd/etc/resolv.conf\\\" caused \\\"open /var/lib/docker/btrfs/subvolumes/9e0aa231ac7e714db5f7a496cfe0c3836d1b28326085f3eeb532747afff1b3bd/etc/resolv.conf: read-only file system\\\"\"": unknown

**Comment by AmedeeBulle** [comment] 2019-04-29 15:43
The message `read-only file system` indicates that something very wrong has happened on the `worker2` node -- I would suspect that the BTRFS filesystem used by docker got corrupted.

I have done some stress tests on my Vagrant/Kubernetes cluster (including a redis image), and cannot reproduce this issue.

This is rather an OS (host or guest) or VirtualBox issue.

Can you reproduce starting from a fresh environment?

If yes, can you provide the version of the components used?
- Guest OS and version
- VirtualBox version
- For the failing guest, kernel version and relevant log files (`/var/log/syslog`, ...)

**Comment by gvenzl** [comment] 2019-08-22 16:24
Hi @AmedeeBulle, given the lack of response, do you think we can close the issue?

**Comment by AmedeeBulle** [comment] 2019-08-23 16:56
I am confident this was a filesystem corruption, not related to Docker / Kubernetes.

Closing. We can re-open / investigate if we have reproducible case and relevant support files.

**Closed by AmedeeBulle** 2019-08-23 16:56 UTC
Labels: kubernetes, more-info-required
