### ISSUE TITLE
Vagrant was unable to mount VirtualBox shared folders.

### ISSUE THREAD

**Issue by desperate-datesless-din0** [oracle/vagrant-boxes#154] opened 2019-10-15 15:23 UTC
Seems this problem has resurfaced again after re-starting vagrant.
```
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:
mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant
The error output from the command was:
/sbin/mount.vboxsf: mounting failed with the error: No such device
```

My Virtualbox is Version 6.0.12 r133076 (Qt5.6.2).

The Oracle 19.3 database vagrant box still runs, and the details of the guest is here:
[root@oracle-19c-vagrant ~]# uname -a
Linux oracle-19c-vagrant 4.14.35-1902.6.6.el7uek.x86_64 #2 SMP Tue Oct 8 07:32:21 PDT 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by gvenzl** [comment] 2019-10-15 16:24
I believe this is a duplicate of #153.

**Comment by PaulNeumann** [comment] 2019-10-15 17:04
@desperate-datesless-din0 
If this is the same problem that I reported in Issue #153, you can get the VirtualBox Guest Additions (including shared folders) working again by running the following in an ssh session:
```bash
sudo yum -y install kernel-uek-devel
sudo /opt/VBoxGuestAdditions-6.0.12/init/vboxadd setup
```
You may need to reboot the box before the Guest Additions work.

I hope this helps!

**Comment by scoter-oracle** [comment] 2019-10-17 23:53
@PaulNeumann thanks for reporting the work-around to this issue.
We're now working to release updated boxes with proper kernel-uek-devel RPM installed.
Hope to have the final solution soon.

**Comment by scoter-oracle** [comment] 2019-10-17 23:54
Further details available in: https://github.com/oracle/vagrant-boxes/issues/153

**Comment by gvenzl** [comment] 2020-01-22 18:16
Hey @scoter-oracle, can this one be closed?

**Closed** 2020-01-22 19:04 UTC
