### ISSUE TITLE
Required package missing in 07-Oct-2019 ol7-latest.box

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-boxes#153] opened 2019-10-14 01:57 UTC
There's an issue with the latest version of the ol7-latest base box (released 07-Oct-2019) that could affect many of the boxes in this repository.  The kernel-uek-devel package isn't included in the base box.  This package is required to rebuild the VirtualBox Guest Additions after a kernel upgrade.  Without it, the GAs (including shared folders) will stop working after a kernel upgrade if the VM is rebooted.

There's already a newer OL7 kernel (4.14.35-1902.6.6.el7uek.x86_64) than the one included in the base box, so all of the boxes in this repository that use OL7 and include a `yum upgrade` statement in the install script will be affected if the 07-Oct-2019 version of ol7-latest.box is used.  The build will succeed, but the Guest Additions will stop working if the VM is rebooted.

The workaround is to add `yum -y install kernel-uek-devel` to the install shell script *before* the `yum upgrade` statement.

(Related:  Although none of the boxes in this repository use Oracle Linux 8 yet, the 07-Oct-2019 version of ol8-latest.box has a similar issue.  The packages elfutils-libelf-devel, gcc and kernel-devel need to be installed before a kernel upgrade for the VirtualBox Guest Additions to be rebuilt automatically.)

**Comment by scoter-oracle** [comment] 2019-10-17 23:54
duplicate of https://github.com/oracle/vagrant-boxes/issues/154

**Closed by scoter-oracle** 2019-10-17 23:54 UTC
Labels: linux
