### ISSUE TITLE
OL 7/8 boxes - How to get shared folders working

### ISSUE THREAD

**Issue by PaulNeumann** [oracle/vagrant-boxes#195] opened 2020-01-13 15:47 UTC
VirtualBox shared folders don't work in the new Oracle Linux 8 box. This is due to
a couple of problems with the 07-Oct-2019 version of the ol8-latest base box, not
the files in this repository.

To get shared folders to work, we need to install some missing packages, then upgrade
the VirtualBox Guest Additions to a version that's compatible with the latest OL 8
kernel. To do that, ssh to the box and run the following commands:

```bash
sudo dnf -y install elfutils-libelf-devel gcc kernel-devel bzip2 wget
wget http://download.virtualbox.org/virtualbox/6.0.14/VBoxGuestAdditions_6.0.14.iso
sudo mkdir /media/VBoxGuestAdditions
sudo mount -o loop,ro VBoxGuestAdditions_6.0.14.iso /media/VBoxGuestAdditions
sudo sh /media/VBoxGuestAdditions/VBoxLinuxAdditions.run
sudo umount /media/VBoxGuestAdditions
sudo rmdir /media/VBoxGuestAdditions
rm VBoxGuestAdditions_6.0.14.iso
```

Notes:

- You can safely ignore any dracut error messages you see when running these commands.
- If you prefer to install version 6.1.0 or 6.1.2 of the Guest Additions, use `6.1.0` or `6.1.2` instead of
`6.0.14` in the commands above.

**Reboot the box after running these commands.** Afterward, shared folders should work.

I'm sure the ol8-latest box will be updated soon, but I hope this helps in the meantime.

**Comment by gvenzl** [comment] 2020-01-13 16:01
I had the same experience last week when building support for the OL8 box. However, I couldn't reproduce it any longer after the first build.

@scoter-oracle, any idea what's wrong with the OL8 box?

**Comment by PaulNeumann** [comment] 2020-01-13 16:22
@AmedeeBulle Thank you for the edit. Much appreciated.

**Comment by scoter-oracle** [comment] 2020-01-13 17:05
@gvenzl our base-box is missing kernel-uek-devel package so, VirtualBox guest-additions cannot be rebuilt on the updated-kernel boot.
We  need to release updated boxes for OL7/OL8

**Comment by scoter-oracle** [comment] 2020-01-13 17:06
It's the same issue #154 opened in the past.
And if you are playing/testing UEK6, the same requires VirtualBox 6.1 Guest-Additions

**Comment by scoter-oracle** [comment] 2020-01-22 19:05
For this open-issue and also same issue on OL7 box we need to release updated base-boxes with "kernel-devel" for RHCK or "kernel-uek-devel" for UEK.

**Comment by purecapitalist** [comment] 2020-02-08 19:57
40,41c40,41
<   config.vm.box = "ol7-latest"
<   config.vm.box_url = "https://yum.oracle.com/boxes/oraclelinux/latest/ol7-latest.box"
---
>   config.vm.box = "ol77"
>   config.vm.box_url = "https://yum.oracle.com/boxes/oraclelinux/latest/ol77.box"

**Comment by Djelibeybi** [comment] 2020-02-08 20:15
> Edit Vagrantfile:

That wouldn't (or shouldn't) work because the URL you're using doesn't exist. @scoter-oracle is correct that you just need to install `kernel-uek-devel` and I confirm that it worked fine for the Vagrant project I'm building that has one of each version (OL6, OL7, OL8).

**Comment by purecapitalist** [comment] 2020-02-08 20:33
I am unclear what you mean when you say that the URL "doesn't exist". I am looking at https://yum.oracle.com/boxes now and it is real.

My change was to the file https://github.com/oracle/vagrant-boxes/OracleDatabase/19.3.0/Vagrantfile

For me, changing the two lines in my local copy of that Vagantfile, as noted above, allowed the build to happen without error using "vagrant up". Beforehand, when the file pointed at "ol7-latest", the /vagrant share never mounted because the vobx was missing the needed extension. 

I'll take your word for it that the missing extension was caused by the missing component.

**Comment by Djelibeybi** [comment] 2020-02-08 21:30
You pasted: `https://yum.oracle.com/boxes/oraclelinux/latest/ol77.box`
The correct URL: `https://yum.oracle.com/boxes/oraclelinux/ol77/ol77.box`

**Comment by purecapitalist** [comment] 2020-02-08 21:38
Oops. I stand corrected. 
Please note I used that incorrect URL in my Vagrantfile and it worked. My diff output was from the before/after edits.

**Comment by Djelibeybi** [comment] 2020-02-08 23:58
> Please note I used that incorrect URL in my Vagrantfile and it worked. My diff output was from the before/after edits.

This suggests that you had a prevoius version of the `ol77.box` stored locally and that previous version had `kernel-uek-devel` installed.

**Comment by purecapitalist** [comment] 2020-02-09 04:08
You are good and correct. I should have known.  As such, I stripped everything and started again. Directories deleted. This time, everything was downloaded and installed from scratch. A reapplied the change with the correct path "ol77/ol77.box". A summary of the activity is below. What else did I do wrong.

`purecaptialist@dhcp-10-154-158-123 19.3.0 % vagrant up
getting Proxy Configuration from Host...
Bringing machine 'oracle-19c-vagrant' up with 'virtualbox' provider...
==> oracle-19c-vagrant: Box 'ol77' could not be found. Attempting to find and install...
    oracle-19c-vagrant: Box Provider: virtualbox
    oracle-19c-vagrant: Box Version: >= 0
==> oracle-19c-vagrant: Box file was not detected as metadata. Adding it directly...
==> oracle-19c-vagrant: Adding box 'ol77' (v0) for provider: virtualbox
    oracle-19c-vagrant: Downloading: https://yum.oracle.com/boxes/oraclelinux/ol77/ol77.box
==> oracle-19c-vagrant: Successfully added box 'ol77' (v0) for 'virtualbox'!
==> oracle-19c-vagrant: Importing base box 'ol77'...
...
==> oracle-19c-vagrant: Machine booted and ready!
==> oracle-19c-vagrant: Checking for guest additions in VM...
...
    oracle-19c-vagrant: Guest Additions Version: 6.0.12
    oracle-19c-vagrant: VirtualBox Version: 6.1
==> oracle-19c-vagrant: Setting hostname...
==> oracle-19c-vagrant: Configuring proxy environment variables...
==> oracle-19c-vagrant: Configuring proxy for Yum...
==> oracle-19c-vagrant: Mounting shared folders...
    oracle-19c-vagrant: /vagrant => /Users/dpallen/vagrant-boxes/OracleDatabase/19.3.0
...
    oracle-19c-vagrant: INSTALLER: Installation complete, database ready to use!
`

**Comment by Djelibeybi** [comment] 2020-02-09 06:12
Looks fine to me. Is it not working? If it's not seeing the shared folders, it's probably the same problem the rest of us are having, I.e, that kernel-uek-devel is missing (or doesn't match the booted kernel).

**Comment by purecapitalist** [comment] 2020-02-09 06:14
/vagrant is visible. The box works. I just want to know if I needed to do anything else.
Thanks!

**Comment by Djelibeybi** [comment] 2020-02-09 06:15
Just enjoy your RAC instance. :)

**Comment by scoter-oracle** [comment] 2020-02-27 11:20
Updated boxes, available at https://yum.oracle.com/boxes , now have "kernel-uek-devel" and/or "kernel-devel" package installed and, in case of updates, the VirtualBox modules are automatically recompiled with updated kernel. Closing the issue.

**Closed by scoter-oracle** 2020-02-27 11:20 UTC
Labels: linux
